server:
  port: 8888

  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: localhost:8848
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  application:
    name: auth-server
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/iot?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver